apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-documents-app
  labels:
    app: django-documents-app
spec:
  replicas: 2  # Number of pods to run
  selector:
    matchLabels:
      app: django-documents-app
  template:
    metadata:
      labels:
        app: django-documents-app
    spec:
      containers:
      - name: django-documents-app
        image: alok772/django-documents-app:latest
        ports:
        - containerPort: 8800
        env:
        - name: DJANGO_SETTINGS_MODULE
          value: "converter.settings"
        - name: DEBUG
          value: "False"
        volumeMounts:
        - name: media-storage
          mountPath: /app/media  # Path in the container for uploaded files
      volumes:
      - name: media-storage
        emptyDir: {}  # This creates a temporary storage volume
